### ISSUE TITLE
predict function fails - subscript out of bounds

### ISSUE THREAD

**Issue by salbeke** [floswald/mnlogit#1]
I am using the mnlogit to generate a model. This is successful. I then have a new dataset that I wish to predict to and I get the error: Error in Z[((ch_k - 1) * size$N + 1):(ch_k * size$N), , drop = FALSE] : subscript out of bounds

Thinking I have a malformed data.frame (that is an mlogit.data object) I tried predicting to the same dataset that I used to fit the model (also an mlogit.data object) and I still receive the error. This seems odd to me, thus this posting of the issue. Do you have any guidance? Thanks for your time.

**Comment by floswald** [comment]
hey

sorry but

I recovered this code from the CRAN archives.
I am not the author of the package.
I am not the maintainer of it either.

( see readme :wink: - you need to contact the package author listed on CRAN)
